#main program
import exceptions

result = exceptions.divide_two_numbers(2, 4)
print(result)


